version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    container_name: django_simple_workout_planner
    build: .
    working_dir: /code
    command: ["./docker/start.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres

volumes:
  postgres_data:
